### ISSUE TITLE
A parameter initializer is only allowed in a function or constructor implementation.

### ISSUE THREAD

**Issue by sharmavikram** [FabianGosebrink/ASPNET-ASPNETCore-AngularJS-Angular#1]
Hello Everyone,

I am try to implement "Angular-Client-Webpack" and it is working fine with "npm-start" and "npm run webpack-dev" command. 

but when i am trying to build with production "npm run webpack-prod" then it shows error.

> A parameter initializer is only allowed in a function or constructor implementation.

**Below is my screenshot:**
![image](https://cloud.githubusercontent.com/assets/8896308/22916084/1416009e-f2a2-11e6-8fad-6b73e1f368a1.png)

Thanks
**Vikram**

**Comment by FabianGosebrink** [comment]
Can you try excluding the node_modules folder explicitly? 

Try to change 

```
{
	test: /\.ts$/,
	use: [
		'awesome-typescript-loader',
		'angular-router-loader?aot=true&genDir=aot/',
		'angular2-template-loader',
	]
},
```
to
```
{
	test: /\.ts$/,
	use: [
		'awesome-typescript-loader',
		'angular-router-loader?aot=true&genDir=aot/',
		'angular2-template-loader',
	],
	exclude: [
		path.resolve(__dirname, "node_modules")
	]
},
```

**Comment by sharmavikram** [comment]
@FabianGosebrink i just change the code of webpack.config.js file. but it returns the same error.

**Comment by FabianGosebrink** [comment]
What is your node and npm version?

Have you done a fresh npm install?

**Comment by sharmavikram** [comment]
My node version v6.9.1 and my npm version is 4.0.5
Yes, i have fresh node install

**Comment by FabianGosebrink** [comment]
In "node_modules\@types\jasmine\package.json" which version are you using (scroll down to the last line)?

**Comment by sharmavikram** [comment]
"version": "2.5.42"

**Comment by FabianGosebrink** [comment]
Just pushed a fix. Can you update and try again?

**Comment by sharmavikram** [comment]
**Thanks** of  Angular-Clinet-Webpack Repo.
i just changed the jasmin version "@types/jasmine": "2.5.42", to "@types/jasmine": "2.5.41",

I have another question related to webpack.dev.js
When I paste css to **CSS Folder** and then import css to import.ts file  and run the command "npm run webpack-dev" it return "cssText.replace is not a function"
Below is my screenshot.
![image](https://cloud.githubusercontent.com/assets/8896308/22959690/3eb268a8-f35e-11e6-82bc-76524f820cd2.png)

**Comment by FabianGosebrink** [comment]
Which "imports.ts" file do you mean?

**Comment by sharmavikram** [comment]
@FabianGosebrink  Sorry for late reply i mean to say it is vendor.ts file.
Everything is working fine, but one issue after compilation of AOT.
when i run AOT folder under "./dist/web/aot" it return error.

> Uncaught reflect-metadata shim is required when using class decorators

![image](https://cloud.githubusercontent.com/assets/8896308/23006904/98eb068c-f42a-11e6-8231-a11bda341823.png)
